### ISSUE TITLE
benchmark read counting bottleneck step

### ISSUE THREAD

**Issue by mattmaurano** [mauranolab/mapping#245]
John,

This step in merge_bamintersect.sh is a bottleneck for samples with high read depth:
num_bam1_reads=$(samtools view -c -F 512 ${normbam})

Can you select a few samples, including some WGS data, and benchmark the line above versus using samtools flagstat?

**Comment by cadley-nyulangone** [comment]
I'm setting up the files so that I can run these benchmarks.   However I
took a look at the source for flagstat first, and I will be surprised if it
is not slower by at least a little bit.   The flagstat source is attached.

flagstat reads through the bam file, and for each read it does several flag
comparisons, one for each of the output lines it generates:

    printf("%lld + %lld in total (QC-passed reads + QC-failed reads)\n",
s->n_reads[0], s->n_reads[1]);
    printf("%lld + %lld secondary\n", s->n_secondary[0], s->n_secondary[1]);
    printf("%lld + %lld supplementary\n", s->n_supp[0], s->n_supp[1]);
    printf("%lld + %lld duplicates\n", s->n_dup[0], s->n_dup[1]);
    printf("%lld + %lld mapped (%s : %s)\n", s->n_mapped[0],
s->n_mapped[1], percent(b0, s->n_mapped[0], s->n_reads[0]), percent(b1,
s->n_mapped[1], s->n_reads[1]));
    printf("%lld + %lld paired in sequencing\n", s->n_pair_all[0],
s->n_pair_all[1]);
    printf("%lld + %lld read1\n", s->n_read1[0], s->n_read1[1]);
    printf("%lld + %lld read2\n", s->n_read2[0], s->n_read2[1]);
    printf("%lld + %lld properly paired (%s : %s)\n", s->n_pair_good[0],
s->n_pair_good[1], percent(b0, s->n_pair_good[0], s->n_pair_all[0]),
percent(b1, s->n_pair_good[1], s->n_pair_all[1]));
    printf("%lld + %lld with itself and mate mapped\n", s->n_pair_map[0],
s->n_pair_map[1]);
    printf("%lld + %lld singletons (%s : %s)\n", s->n_sgltn[0],
s->n_sgltn[1], percent(b0, s->n_sgltn[0], s->n_pair_all[0]), percent(b1,
s->n_sgltn[1], s->n_pair_all[1]));
    printf("%lld + %lld with mate mapped to a different chr\n",
s->n_diffchr[0], s->n_diffchr[1]);
    printf("%lld + %lld with mate mapped to a different chr (mapQ>=5)\n",
s->n_diffhigh[0], s->n_diffhigh[1]);


Here's where it does the flag comparison work:

#define flagstat_loop(s, c) do {                                        \
        int w = ((c)->flag & BAM_FQCFAIL)? 1 : 0;                       \
        ++(s)->n_reads[w];                                              \
        if ((c)->flag & BAM_FSECONDARY ) {                              \
            ++(s)->n_secondary[w];                                      \
        } else if ((c)->flag & BAM_FSUPPLEMENTARY ) {                   \
            ++(s)->n_supp[w];                                           \
        } else if ((c)->flag & BAM_FPAIRED) {                           \
            ++(s)->n_pair_all[w];                                       \
            if (((c)->flag & BAM_FPROPER_PAIR) && !((c)->flag & BAM_FUNMAP)
) ++(s)->n_pair_good[w];    \
            if ((c)->flag & BAM_FREAD1) ++(s)->n_read1[w];              \
            if ((c)->flag & BAM_FREAD2) ++(s)->n_read2[w];              \
            if (((c)->flag & BAM_FMUNMAP) && !((c)->flag & BAM_FUNMAP))
++(s)->n_sgltn[w];  \
            if (!((c)->flag & BAM_FUNMAP) && !((c)->flag & BAM_FMUNMAP)) { \
                ++(s)->n_pair_map[w];                                   \
                if ((c)->mtid != (c)->tid) {                            \
                    ++(s)->n_diffchr[w];                                \
                    if ((c)->qual >= 5) ++(s)->n_diffhigh[w];           \
                }                                                       \
            }                                                           \
        }                                                               \
        if (!((c)->flag & BAM_FUNMAP)) ++(s)->n_mapped[w];              \
        if ((c)->flag & BAM_FDUP) ++(s)->n_dup[w];                      \
    } while (0)


Those counters are struct pointers to small arrays, so there's some work
going on there too.

samtools view -c -F 512  only does one flag comparison, and increments only
one integer counter.  So I'll be surprised if flagstat turns out to be
faster.

I think flagstat would be useful if you needed stats for multiple flags,
because it would save you from calling samtools view multiple times.

John

**Comment by mattmaurano** [comment]
OK, that's helpful. Flagstat is definitely not fast for big bams, but I had thought it used info from the .bai to speed up; sounds like that was wrong. It would still be good to run a simple head-to-head benchmark on an single bam to confirm.

An alternative approach is to move the read count calculation into submit, then pass it as a new argument to merge. This effectively parallelizes it rather than doing it in the critical path once everything else has finished.

**Comment by cadley-nyulangone** [comment]
I ran the mm10.bam file of BS07520A a few times.  Depending on how busy the
cluster was, it took 22-25 minutes to process.  samtools view and flagstat
were always within a minute of each other.   I think reading the file
dominates what little computation is required.

**Comment by mattmaurano** [comment]
OK. Can you submit a PR that moves the read count calculation into submit, then passes the result as a new argument to merge?
